[connections.postgresql]
dialect = "postgresql"
host = "ep-muddy-snowflake-a8nfzvy9-pooler.eastus2.azure.neon.tech"
port = "5432"
database = "neondb"
username = "neondb_owner"   
password = "npg_lIX7tWQGMZo6"

[passwords]
app_password = "24719303"
