DB_HOST = 'ep-long-credit-a80dfkpn-pooler.eastus2.azure.neon.tech'
DB_PORT = '5432'
DB_NAME = 'neondb'
DB_USER = 'neondb_owner'
DB_PASSWORD = 'npg_qWRk0Df8jHcY'
db_connection_string = 'postgresql://neondb_owner:npg_qWRk0Df8jHcY@ep-long-credit-a80dfkpn-pooler.eastus2.azure.neon.tech/neondb?sslmode=require'
