DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "options_analyzer_db"
DB_USER = "options_app_user"
DB_PASSWORD = "Morpheus321"  # <<< MAKE SURE THIS IS YOUR CORRECT PASSWORD
db_connection_string = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
